import numpy as np
import os

def InpWrite(matidx, modname):
    print(modname)
    filedir = "inpfiles"
    if os.path.exists(filedir):
        InpPF = open("".join([filedir, "/", modname, "_sets.inp"]), 'w')
    else:
        os.makedirs(filedir)
        InpPF = open("".join([filedir, "/", modname, "_sets.inp"]), 'w')
    InpPF.write('** ----------------------------------------------------------------')
    InpPF.write('\n')
    InpPF.write('** Yutai Su (buaa_syt@126.com)')
    InpPF.write('\n')
    InpPF.write('** Generated by Python')
    InpPF.write('\n')
    InpPF.write('** ----------------------------------------------------------------')
    InpPF.write('\n')
    matlist = np.unique(matidx)
    for matii in matlist:
        if matii == 0:
            InpPF.write('*Elset, elset=Pore')
        elif matii == 1:
            InpPF.write('*Elset, elset=Mortar')
        elif matii == 2:
            InpPF.write('*Elset, elset=ITZ')
        elif matii == 3:
            InpPF.write('*Elset, elset=Aggre')
        InpPF.write('\n')
        xx, yy, zz = np.where(matidx == matii)
        lx = matidx.shape[0]
        ly = matidx.shape[1]
        lz = matidx.shape[2]
        print(lx, ly, lz)
        xx, yy, zz = np.where(matidx == matii)
        yy_ab_order = lz-zz-1
        zz_ab_order = lx-xx-1
        xx_ab_order = ly-yy-1
        EleSetNum = 1+yy_ab_order+zz_ab_order*lz+xx_ab_order*lz*lx
        i = 0
        while i < len(EleSetNum):
            k = 0
            while k < 16:
                InpPF.write(' ')
                if i < len(EleSetNum):
                    InpPF.write(str(EleSetNum[i]))
                    InpPF.write(',')
                else:
                    break
                i += 1
                k += 1
            InpPF.write('\n')
    InpPF.close()
